DOMAIN = "benni_scene_presets"
NAME = "Benni Scene Presets"

PANEL_URL = "/benni_scene_presets_panel.js"

SERVICE_APPLY_PRESET = "apply_preset"
SERVICE_START_DYNAMIC_SCENE = "start_dynamic_scene"
SERVICE_STOP_DYNAMIC_SCENE = "stop_dynamic_scene"
SERVICE_STOP_ALL_DYNAMIC_SCENES = "stop_all_dynamic_scenes"
SERVICE_STOP_DYNAMIC_SCENES_FOR_TARGETS = "stop_dynamic_scenes_for_targets"
SERVICE_GET_DYNAMIC_SCENES = "get_dynamic_scenes"
SERVICE_APPLY_LOOK = "apply_look"
SERVICE_STOP_LOOK = "stop_look"

ATTR_SCENE_PRESET_ID = "preset_id"
ATTR_TARGETS = "targets"
ATTR_BRIGHTNESS = "brightness"
ATTR_TRANSITION = "transition"
ATTR_INITIAL_TRANSITION = "initial_transition"
ATTR_SHUFFLE = "shuffle"
ATTR_SMART_SHUFFLE = "smart_shuffle"
ATTR_INTERVAL = "interval"

ATTR_DYNAMIC_SCENE_ID = "id"
ATTR_LOOK_ID = "look_id"
